// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhL_tkFlnLyp89cx-4v4po5srFowejqxU',
    appId: '1:15781080528:android:57961d0bac09f2faaaddd5',
    messagingSenderId: '15781080528',
    projectId: 'quirkey-3ab2c',
    storageBucket: 'quirkey-3ab2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF2rvEtZb0ewPf2nDDl6OvrrcPlpzVDyw',
    appId: '1:15781080528:ios:c1ec92592ab9a265aaddd5',
    messagingSenderId: '15781080528',
    projectId: 'quirkey-3ab2c',
    storageBucket: 'quirkey-3ab2c.appspot.com',
    iosBundleId: 'com.example.quirkey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF2rvEtZb0ewPf2nDDl6OvrrcPlpzVDyw',
    appId: '1:15781080528:ios:c1ec92592ab9a265aaddd5',
    messagingSenderId: '15781080528',
    projectId: 'quirkey-3ab2c',
    storageBucket: 'quirkey-3ab2c.appspot.com',
    iosBundleId: 'com.example.quirkey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzNI4H-rZu3s1HD1wQH6cdwqYaN80gZdI',
    appId: '1:15781080528:web:6534f626ae896b05aaddd5',
    messagingSenderId: '15781080528',
    projectId: 'quirkey-3ab2c',
    authDomain: 'quirkey-3ab2c.firebaseapp.com',
    storageBucket: 'quirkey-3ab2c.appspot.com',
    measurementId: 'G-ZDH4C8T2VP',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCzNI4H-rZu3s1HD1wQH6cdwqYaN80gZdI',
    appId: '1:15781080528:web:1dd18ec1e89c3dcdaaddd5',
    messagingSenderId: '15781080528',
    projectId: 'quirkey-3ab2c',
    authDomain: 'quirkey-3ab2c.firebaseapp.com',
    storageBucket: 'quirkey-3ab2c.appspot.com',
    measurementId: 'G-7Q1BWWB7NF',
  );
}
